openapi: 3.0.3
info:
  title: OpenAPI Example
  description: OpenAPI Example
  version: 1.0.0
  termsOfService: https://example.com/terms
  contact:
    name: Nazar Lipkovskyy
    url: https://example.com
    email: nazjara@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://dev.example.com
    description: Development Server
  - url: https://qa.example.com
    description: QA Server
  - url: https://prod.example.com
    description: Production Server
paths:
  /v1/customers:
    get:
      responses:
        200:
          description: List of Customers
          content:
            application/json:
              schema:
                type: array
                minItems: 1
                maxItems: 100
                items:
                  type: object
                  properties:
                    firstName:
                      type: string
                      minLength: 2
                      maxLength: 100
                    lastName:
                      type: string
                      minLength: 2
                      maxLength: 100
                    address:
                      type: object
                      properties:
                        country:
                          type: string
                          example: Ukraine
                        city:
                          type: string
                          example: Lviv
                        zipCode:
                          type: string
                          example: 79000
                        stateCode:
                          type: string
                          minLength: 2
                          maxLength: 2
                          description: 2 letter state code
                          enum:
                            - AL
                            - AK
                            - AZ
                            - AR
                            - CA
                  description: Customer Name
                  minLength: 2
                  maxLength: 100
  /v1/beers:
    get:
      responses:
        200:
          description: List of Beers
          content:
            application/json:
              schema:
                type: array
                minItems: 1
                maxItems: 100
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    style:
                      type: string
                      enum:
                        - ALE
                        - PALE_ALE
                        - IPA
                        - WHEAT
                        - LAGER
                    upc:
                      type: string
                    price:
                      type: number
                      format: float
                    quantityOnHand:
                      type: number
                      format: int32
                    brewery:
                      type: object
                      properties:
                        name:
                          type: string
                        location:
                          type: string

        404:
          description: Beers not found