/*
 * OpenAPI Example
 * OpenAPI Example
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nazjara@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Beer;
import org.openapitools.client.model.BeerPagedList;
import org.openapitools.client.model.Customer;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BeerApi
 */
@Ignore
public class BeerApiTest {

    private final BeerApi api = new BeerApi();

    
    /**
     * Create beer
     *
     * Create **beer**
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createBeerV1Test() throws ApiException {
        Beer beer = null;
        Customer response = api.createBeerV1(beer);

        // TODO: test validations
    }
    
    /**
     * Delete beer by id
     *
     * Delete **beer** by id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteBeerByIdV1Test() throws ApiException {
        UUID beerId = null;
        api.deleteBeerByIdV1(beerId);

        // TODO: test validations
    }
    
    /**
     * Find beer by id
     *
     * Find **beer** by id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBeerByIdV1Test() throws ApiException {
        UUID beerId = null;
        Beer response = api.getBeerByIdV1(beerId);

        // TODO: test validations
    }
    
    /**
     * Get list of beers
     *
     * Get list of **beers** in the system
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listBeersV1Test() throws ApiException {
        Integer pageNumber = null;
        Integer pageSize = null;
        BeerPagedList response = api.listBeersV1(pageNumber, pageSize);

        // TODO: test validations
    }
    
    /**
     * Update beer by id
     *
     * Update **beer** by id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateBeerByIdV1Test() throws ApiException {
        UUID beerId = null;
        Beer beer = null;
        Beer response = api.updateBeerByIdV1(beerId, beer);

        // TODO: test validations
    }
    
}
