/*
 * OpenAPI Example
 * OpenAPI Example
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nazjara@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Customer;
import org.openapitools.client.model.CustomerPagedList;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CustomerApi
 */
@Ignore
public class CustomerApiTest {

    private final CustomerApi api = new CustomerApi();

    
    /**
     * Create customer
     *
     * Create **customer**
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createCustomerV1Test() throws ApiException {
        Customer customer = null;
        Customer response = api.createCustomerV1(customer);

        // TODO: test validations
    }
    
    /**
     * Delete customer by id
     *
     * Delete **customer** by id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCustomerByIdV1Test() throws ApiException {
        UUID customerId = null;
        api.deleteCustomerByIdV1(customerId);

        // TODO: test validations
    }
    
    /**
     * Find customer by id
     *
     * Find **customer** by id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCustomerByIdV1Test() throws ApiException {
        UUID customerId = null;
        Customer response = api.getCustomerByIdV1(customerId);

        // TODO: test validations
    }
    
    /**
     * Get all customers
     *
     * Get all **customers** in the system
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listCustomersV1Test() throws ApiException {
        Integer pageNumber = null;
        Integer pageSize = null;
        CustomerPagedList response = api.listCustomersV1(pageNumber, pageSize);

        // TODO: test validations
    }
    
    /**
     * Update customer by id
     *
     * Update **customer** by id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateCustomerByIdV1Test() throws ApiException {
        UUID customerId = null;
        Customer customer = null;
        Customer response = api.updateCustomerByIdV1(customerId, customer);

        // TODO: test validations
    }
    
}
